name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [macos-26, macos-26-intel]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Install ShellCheck
        run: brew install shellcheck
      - name: Check
        run: make check
